# Quick test configuration
seed: 42
psd_model: 'one_over_f'
horizon: 1.0
target_gate: 'hadamard'

task_dist_type: 'uniform'
alpha_range: [0.5, 2.0]
A_range: [0.05, 0.3]
omega_c_range: [2.0, 8.0]

task_feature_dim: 3
hidden_dim: 32
n_hidden_layers: 2
n_segments: 10
n_controls: 2
output_scale: 0.5

inner_lr: 0.01
inner_steps: 3
meta_lr: 0.001
first_order: true

n_iterations: 10
tasks_per_batch: 2
n_support: 5
n_query: 5
log_interval: 5
val_interval: 10

save_dir: 'checkpoints_test'
integration_method: 'RK45'
